server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8787/eureka
    register-with-eureka: true

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: rating-data-service
          uri: lb://rating-data-service
          predicates:
            - Path=/movies

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000